plugins {
	id 'java'
	id 'jacoco'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'info.solidsoft.pitest' version '1.19.0'
}

group = 'com.redis-repo'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-redis-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.assertj:assertj-core'
}

test {
	useJUnitPlatform()
	reports {
		html.required = true
		junitXml.required = true
	}
	finalizedBy(tasks.jacocoTestReport)
}

pitest {
	targetClasses = ['com.redis_repo.crud.*']
	outputFormats = ['HTML']
	timestampedReports = false
	junit5PluginVersion = '1.2.3'
}